/**
 * index.html is the single source for the game page; shilploka.html is only
 * an address, generated by scripts/vite_legacy_entry.js.
 *
 * WHY these tests: the hand-edited copy was removed. If someone re-adds it,
 * or the generated alias stops working, the verify scripts (which open
 * /shilploka.html) and any old links would break or drift - these catch that
 * on `npm test`, by really building and really serving the project.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { build, createServer } from 'vite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { LEGACY_ENTRY, LEGACY_ENTRY_HTML } from '../scripts/vite_legacy_entry.js';

const ROOT = path.resolve(import.meta.dirname, '..');

describe('HTML entry', () => {
  it('index.html is the only entry page in the repo', () => {
    expect(fs.existsSync(path.join(ROOT, 'index.html'))).toBe(true);
    expect(fs.existsSync(path.join(ROOT, LEGACY_ENTRY))).toBe(false);
  });

  describe('npm run build', () => {
    const outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'shilploka-build-'));
    beforeAll(async () => {
      await build({ root: ROOT, logLevel: 'silent', build: { outDir, emptyOutDir: true } });
    }, 60_000);
    afterAll(() => fs.rmSync(outDir, { recursive: true, force: true }));

    it('emits the real single-file game as index.html', () => {
      const html = fs.readFileSync(path.join(outDir, 'index.html'), 'utf8');
      expect(html.length).toBeGreaterThan(100_000);           // three.js + game inlined
      expect(html).not.toMatch(/<script[^>]+src=/);           // nothing external to load
    });

    it('generates shilploka.html as a small forwarder to index.html', () => {
      const alias = fs.readFileSync(path.join(outDir, LEGACY_ENTRY), 'utf8');
      expect(alias).toBe(LEGACY_ENTRY_HTML);
      expect(alias.length).toBeLessThan(1024);                // not a second 640 KB copy
      // The query string survives, so ?mobile=true links keep working.
      expect(alias).toContain("location.replace('index.html' + location.search + location.hash)");
    });

    it('emits nothing else (the itch.io zip takes all of dist/)', () => {
      expect(fs.readdirSync(outDir).sort()).toEqual(['index.html', LEGACY_ENTRY].sort());
    });
  });

  // Run twice. 'spa' is Vite's default and this project's config. 'mpa' turns
  // off Vite's catch-all fallback (which would answer ANY unknown path, typos
  // included, with index.html) - only there does a pass prove that the alias
  // itself does the work. Without the plugin the 'mpa' case gets a 404.
  describe.each(['spa', 'mpa'])('npm run dev (appType %s)', (appType) => {
    let server;
    let base;
    beforeAll(async () => {
      server = await createServer({ root: ROOT, appType, logLevel: 'silent', server: { port: 0, host: '127.0.0.1' } });
      await server.listen();
      base = server.resolvedUrls.local[0].replace(/\/$/, '');
    }, 30_000);
    afterAll(() => server?.close());

    it.each(['/shilploka.html', '/shilploka.html?mobile=true'])(
      '%s serves the same page as /index.html (what the verify scripts open)',
      async (url) => {
        const [alias, real] = await Promise.all([
          fetch(base + url, { headers: { accept: 'text/html' } }),
          fetch(base + '/index.html', { headers: { accept: 'text/html' } }).then(r => r.text()),
        ]);
        expect(alias.status).toBe(200);
        const html = await alias.text();
        expect(html).toBe(real);
        expect(html).toContain('src/shilploka/shilploka_main.js');
      }
    );
  });
});
